// Code generated by protoc-gen-go. DO NOT EDIT.
// source: crawler/crawler.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CrawlRequest struct {
	Source               string   `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Urls                 []string `protobuf:"bytes,2,rep,name=urls,proto3" json:"urls,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrawlRequest) Reset()         { *m = CrawlRequest{} }
func (m *CrawlRequest) String() string { return proto.CompactTextString(m) }
func (*CrawlRequest) ProtoMessage()    {}
func (*CrawlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_951b7949eb1aa3c9, []int{0}
}

func (m *CrawlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrawlRequest.Unmarshal(m, b)
}
func (m *CrawlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrawlRequest.Marshal(b, m, deterministic)
}
func (m *CrawlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrawlRequest.Merge(m, src)
}
func (m *CrawlRequest) XXX_Size() int {
	return xxx_messageInfo_CrawlRequest.Size(m)
}
func (m *CrawlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CrawlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CrawlRequest proto.InternalMessageInfo

func (m *CrawlRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *CrawlRequest) GetUrls() []string {
	if m != nil {
		return m.Urls
	}
	return nil
}

type CrawlResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 []*Song  `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrawlResponse) Reset()         { *m = CrawlResponse{} }
func (m *CrawlResponse) String() string { return proto.CompactTextString(m) }
func (*CrawlResponse) ProtoMessage()    {}
func (*CrawlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_951b7949eb1aa3c9, []int{1}
}

func (m *CrawlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrawlResponse.Unmarshal(m, b)
}
func (m *CrawlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrawlResponse.Marshal(b, m, deterministic)
}
func (m *CrawlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrawlResponse.Merge(m, src)
}
func (m *CrawlResponse) XXX_Size() int {
	return xxx_messageInfo_CrawlResponse.Size(m)
}
func (m *CrawlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CrawlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CrawlResponse proto.InternalMessageInfo

func (m *CrawlResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CrawlResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CrawlResponse) GetData() []*Song {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*CrawlRequest)(nil), "crawler.CrawlRequest")
	proto.RegisterType((*CrawlResponse)(nil), "crawler.CrawlResponse")
}

func init() { proto.RegisterFile("crawler/crawler.proto", fileDescriptor_951b7949eb1aa3c9) }

var fileDescriptor_951b7949eb1aa3c9 = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0xd5, 0xa6, 0x34, 0xf4, 0x80, 0xc5, 0xa8, 0x95, 0xd5, 0x01, 0x45, 0x9d, 0xb2, 0x34,
	0x16, 0xa9, 0x40, 0x88, 0x0d, 0xfa, 0x0f, 0xcc, 0xc6, 0xe6, 0xb8, 0xc6, 0x8d, 0x48, 0x62, 0xe3,
	0xb3, 0x85, 0xc4, 0xaf, 0x47, 0x71, 0x12, 0x09, 0xb1, 0xf8, 0xee, 0x7b, 0x4f, 0x67, 0xbd, 0x3b,
	0x58, 0x4b, 0x27, 0xbe, 0x1b, 0xe5, 0xd8, 0x58, 0x0b, 0xeb, 0x8c, 0x37, 0x24, 0x1d, 0x71, 0x7b,
	0x2b, 0x6c, 0xcd, 0xd0, 0x74, 0x3a, 0x3e, 0x83, 0xbb, 0x7b, 0x86, 0xeb, 0x63, 0xef, 0x73, 0xf5,
	0x15, 0x14, 0x7a, 0xb2, 0x81, 0x25, 0x9a, 0xe0, 0xa4, 0xa2, 0xb3, 0x6c, 0x96, 0xaf, 0xf8, 0x48,
	0x84, 0xc0, 0x22, 0xb8, 0x06, 0xe9, 0x3c, 0x4b, 0xf2, 0x15, 0x8f, 0xfd, 0x4e, 0xc2, 0xcd, 0x38,
	0x8b, 0xd6, 0x74, 0xa8, 0x08, 0x85, 0x14, 0x83, 0x94, 0x0a, 0x31, 0x4e, 0x5f, 0xf2, 0x09, 0x7b,
	0xa7, 0x55, 0x88, 0x42, 0x2b, 0x3a, 0x8f, 0xff, 0x4e, 0x48, 0xee, 0x60, 0x71, 0x12, 0x5e, 0xd0,
	0x24, 0x4b, 0xf2, 0xab, 0x12, 0x8a, 0x98, 0xed, 0xcd, 0x74, 0x9a, 0x47, 0xbd, 0x7c, 0x81, 0xf4,
	0x38, 0x2c, 0x40, 0x1e, 0xe1, 0x22, 0xb6, 0x64, 0x5d, 0x4c, 0x2b, 0xfe, 0xcd, 0xbe, 0xdd, 0xfc,
	0x97, 0x87, 0x58, 0xaf, 0xf7, 0xef, 0x4c, 0xd7, 0xfe, 0x1c, 0xaa, 0x42, 0x9a, 0x96, 0xf9, 0xb3,
	0xa8, 0x4f, 0x3f, 0xa2, 0x2e, 0x9f, 0x1e, 0x58, 0x5f, 0xf7, 0xad, 0x3d, 0xec, 0xe3, 0x31, 0xaa,
	0xf0, 0xc1, 0xec, 0xa7, 0x66, 0xb6, 0xaa, 0x96, 0x51, 0x38, 0xfc, 0x06, 0x00, 0x00, 0xff, 0xff,
	0x26, 0x26, 0xe2, 0x2d, 0x54, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CrawlerClient is the client API for Crawler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CrawlerClient interface {
	Crawl(ctx context.Context, in *CrawlRequest, opts ...grpc.CallOption) (*CrawlResponse, error)
}

type crawlerClient struct {
	cc *grpc.ClientConn
}

func NewCrawlerClient(cc *grpc.ClientConn) CrawlerClient {
	return &crawlerClient{cc}
}

func (c *crawlerClient) Crawl(ctx context.Context, in *CrawlRequest, opts ...grpc.CallOption) (*CrawlResponse, error) {
	out := new(CrawlResponse)
	err := c.cc.Invoke(ctx, "/crawler.Crawler/Crawl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrawlerServer is the server API for Crawler service.
type CrawlerServer interface {
	Crawl(context.Context, *CrawlRequest) (*CrawlResponse, error)
}

// UnimplementedCrawlerServer can be embedded to have forward compatible implementations.
type UnimplementedCrawlerServer struct {
}

func (*UnimplementedCrawlerServer) Crawl(ctx context.Context, req *CrawlRequest) (*CrawlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Crawl not implemented")
}

func RegisterCrawlerServer(s *grpc.Server, srv CrawlerServer) {
	s.RegisterService(&_Crawler_serviceDesc, srv)
}

func _Crawler_Crawl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrawlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlerServer).Crawl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crawler.Crawler/Crawl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlerServer).Crawl(ctx, req.(*CrawlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Crawler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "crawler.Crawler",
	HandlerType: (*CrawlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Crawl",
			Handler:    _Crawler_Crawl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crawler/crawler.proto",
}
