// Code generated by protoc-gen-go. DO NOT EDIT.
// source: song.proto

package song

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SongRequestParams struct {
	Genre                string   `protobuf:"bytes,1,opt,name=genre,proto3" json:"genre,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SongRequestParams) Reset()         { *m = SongRequestParams{} }
func (m *SongRequestParams) String() string { return proto.CompactTextString(m) }
func (*SongRequestParams) ProtoMessage()    {}
func (*SongRequestParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_61053d46a4955649, []int{0}
}

func (m *SongRequestParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SongRequestParams.Unmarshal(m, b)
}
func (m *SongRequestParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SongRequestParams.Marshal(b, m, deterministic)
}
func (m *SongRequestParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SongRequestParams.Merge(m, src)
}
func (m *SongRequestParams) XXX_Size() int {
	return xxx_messageInfo_SongRequestParams.Size(m)
}
func (m *SongRequestParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SongRequestParams.DiscardUnknown(m)
}

var xxx_messageInfo_SongRequestParams proto.InternalMessageInfo

func (m *SongRequestParams) GetGenre() string {
	if m != nil {
		return m.Genre
	}
	return ""
}

type GetSongsResponse struct {
	Data                 []*Song  `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSongsResponse) Reset()         { *m = GetSongsResponse{} }
func (m *GetSongsResponse) String() string { return proto.CompactTextString(m) }
func (*GetSongsResponse) ProtoMessage()    {}
func (*GetSongsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61053d46a4955649, []int{1}
}

func (m *GetSongsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSongsResponse.Unmarshal(m, b)
}
func (m *GetSongsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSongsResponse.Marshal(b, m, deterministic)
}
func (m *GetSongsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSongsResponse.Merge(m, src)
}
func (m *GetSongsResponse) XXX_Size() int {
	return xxx_messageInfo_GetSongsResponse.Size(m)
}
func (m *GetSongsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSongsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSongsResponse proto.InternalMessageInfo

func (m *GetSongsResponse) GetData() []*Song {
	if m != nil {
		return m.Data
	}
	return nil
}

type Song struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ArtistsNames         string   `protobuf:"bytes,3,opt,name=artists_names,json=artistsNames,proto3" json:"artists_names,omitempty"`
	Thumbnail            string   `protobuf:"bytes,4,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	ThumbnailMedium      string   `protobuf:"bytes,5,opt,name=thumbnail_medium,json=thumbnailMedium,proto3" json:"thumbnail_medium,omitempty"`
	Lyric                string   `protobuf:"bytes,6,opt,name=lyric,proto3" json:"lyric,omitempty"`
	Duration             int32    `protobuf:"varint,7,opt,name=duration,proto3" json:"duration,omitempty"`
	Genres               []*Genre `protobuf:"bytes,8,rep,name=genres,proto3" json:"genres,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Song) Reset()         { *m = Song{} }
func (m *Song) String() string { return proto.CompactTextString(m) }
func (*Song) ProtoMessage()    {}
func (*Song) Descriptor() ([]byte, []int) {
	return fileDescriptor_61053d46a4955649, []int{2}
}

func (m *Song) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Song.Unmarshal(m, b)
}
func (m *Song) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Song.Marshal(b, m, deterministic)
}
func (m *Song) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Song.Merge(m, src)
}
func (m *Song) XXX_Size() int {
	return xxx_messageInfo_Song.Size(m)
}
func (m *Song) XXX_DiscardUnknown() {
	xxx_messageInfo_Song.DiscardUnknown(m)
}

var xxx_messageInfo_Song proto.InternalMessageInfo

func (m *Song) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Song) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Song) GetArtistsNames() string {
	if m != nil {
		return m.ArtistsNames
	}
	return ""
}

func (m *Song) GetThumbnail() string {
	if m != nil {
		return m.Thumbnail
	}
	return ""
}

func (m *Song) GetThumbnailMedium() string {
	if m != nil {
		return m.ThumbnailMedium
	}
	return ""
}

func (m *Song) GetLyric() string {
	if m != nil {
		return m.Lyric
	}
	return ""
}

func (m *Song) GetDuration() int32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Song) GetGenres() []*Genre {
	if m != nil {
		return m.Genres
	}
	return nil
}

type Streaming struct {
	Q128                 string   `protobuf:"bytes,1,opt,name=q128,proto3" json:"q128,omitempty"`
	Q320                 string   `protobuf:"bytes,2,opt,name=q320,proto3" json:"q320,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Streaming) Reset()         { *m = Streaming{} }
func (m *Streaming) String() string { return proto.CompactTextString(m) }
func (*Streaming) ProtoMessage()    {}
func (*Streaming) Descriptor() ([]byte, []int) {
	return fileDescriptor_61053d46a4955649, []int{3}
}

func (m *Streaming) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Streaming.Unmarshal(m, b)
}
func (m *Streaming) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Streaming.Marshal(b, m, deterministic)
}
func (m *Streaming) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Streaming.Merge(m, src)
}
func (m *Streaming) XXX_Size() int {
	return xxx_messageInfo_Streaming.Size(m)
}
func (m *Streaming) XXX_DiscardUnknown() {
	xxx_messageInfo_Streaming.DiscardUnknown(m)
}

var xxx_messageInfo_Streaming proto.InternalMessageInfo

func (m *Streaming) GetQ128() string {
	if m != nil {
		return m.Q128
	}
	return ""
}

func (m *Streaming) GetQ320() string {
	if m != nil {
		return m.Q320
	}
	return ""
}

type Genre struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Alias                string   `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	Link                 string   `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Genre) Reset()         { *m = Genre{} }
func (m *Genre) String() string { return proto.CompactTextString(m) }
func (*Genre) ProtoMessage()    {}
func (*Genre) Descriptor() ([]byte, []int) {
	return fileDescriptor_61053d46a4955649, []int{4}
}

func (m *Genre) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Genre.Unmarshal(m, b)
}
func (m *Genre) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Genre.Marshal(b, m, deterministic)
}
func (m *Genre) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Genre.Merge(m, src)
}
func (m *Genre) XXX_Size() int {
	return xxx_messageInfo_Genre.Size(m)
}
func (m *Genre) XXX_DiscardUnknown() {
	xxx_messageInfo_Genre.DiscardUnknown(m)
}

var xxx_messageInfo_Genre proto.InternalMessageInfo

func (m *Genre) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Genre) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Genre) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *Genre) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func init() {
	proto.RegisterType((*SongRequestParams)(nil), "song.SongRequestParams")
	proto.RegisterType((*GetSongsResponse)(nil), "song.GetSongsResponse")
	proto.RegisterType((*Song)(nil), "song.Song")
	proto.RegisterType((*Streaming)(nil), "song.Streaming")
	proto.RegisterType((*Genre)(nil), "song.Genre")
}

func init() { proto.RegisterFile("song.proto", fileDescriptor_61053d46a4955649) }

var fileDescriptor_61053d46a4955649 = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x4d, 0xa1, 0x45, 0x18, 0x50, 0x71, 0x62, 0x74, 0x43, 0x8c, 0x21, 0xe5, 0x02, 0x17, 0xa2,
	0xe5, 0x62, 0xe2, 0x07, 0x70, 0x30, 0x1a, 0x53, 0xe2, 0x99, 0x2c, 0x74, 0x53, 0x37, 0xb6, 0x5b,
	0xd8, 0xdd, 0x9a, 0xf8, 0xd9, 0xfe, 0x81, 0xd9, 0x69, 0x8b, 0x18, 0x6f, 0xf3, 0x5e, 0x5f, 0x66,
	0xe7, 0xbd, 0x57, 0x00, 0x53, 0xa8, 0x74, 0xbe, 0xd3, 0x85, 0x2d, 0xd0, 0x77, 0x73, 0x38, 0x83,
	0x8b, 0x55, 0xa1, 0xd2, 0x58, 0xec, 0x4b, 0x61, 0xec, 0x2b, 0xd7, 0x3c, 0x37, 0x78, 0x09, 0x41,
	0x2a, 0x94, 0x16, 0xcc, 0x1b, 0x7b, 0xd3, 0x5e, 0x5c, 0x81, 0x30, 0x82, 0xe1, 0x52, 0x58, 0xa7,
	0x36, 0xb1, 0x30, 0xbb, 0x42, 0x19, 0x81, 0xb7, 0xe0, 0x27, 0xdc, 0x72, 0xe6, 0x8d, 0xdb, 0xd3,
	0x7e, 0x04, 0x73, 0xda, 0x4f, 0x0b, 0x89, 0x0f, 0xbf, 0x3d, 0xf0, 0x1d, 0xc4, 0x33, 0x68, 0xc9,
	0xa4, 0xde, 0xd7, 0x92, 0x89, 0x7b, 0xc2, 0x4a, 0x9b, 0x09, 0xd6, 0xaa, 0x9e, 0x20, 0x80, 0x13,
	0x38, 0xe5, 0xda, 0x4a, 0x63, 0xcd, 0x5a, 0xf1, 0x5c, 0x18, 0xd6, 0xa6, 0xaf, 0x83, 0x9a, 0x7c,
	0x71, 0x1c, 0xde, 0x40, 0xcf, 0xbe, 0x97, 0xf9, 0x46, 0x71, 0x99, 0x31, 0x9f, 0x04, 0xbf, 0x04,
	0xce, 0x60, 0x78, 0x00, 0xeb, 0x5c, 0x24, 0xb2, 0xcc, 0x59, 0x40, 0xa2, 0xf3, 0x03, 0xff, 0x4c,
	0xb4, 0xbb, 0x21, 0xfb, 0xd2, 0x72, 0xcb, 0x3a, 0xd5, 0x0d, 0x04, 0x70, 0x04, 0xdd, 0xa4, 0xd4,
	0xdc, 0xca, 0x42, 0xb1, 0x93, 0xb1, 0x37, 0x0d, 0xe2, 0x03, 0xc6, 0x09, 0x74, 0x28, 0x0b, 0xc3,
	0xba, 0x64, 0xb8, 0x5f, 0x19, 0x5e, 0x3a, 0x2e, 0xae, 0x3f, 0x85, 0x0b, 0xe8, 0xad, 0xac, 0x16,
	0x3c, 0x97, 0x2a, 0x45, 0x04, 0x7f, 0x7f, 0x1f, 0x3d, 0xd4, 0xce, 0x69, 0x26, 0x6e, 0x11, 0xdd,
	0xd5, 0xd6, 0x69, 0x0e, 0xdf, 0x20, 0xa0, 0x2d, 0xff, 0x82, 0x42, 0xf0, 0x5d, 0x14, 0x8d, 0xd8,
	0xcd, 0xee, 0x70, 0x9e, 0x49, 0xde, 0xc4, 0x53, 0x01, 0xa7, 0xcc, 0xa4, 0xfa, 0xa8, 0x23, 0xa1,
	0x39, 0x7a, 0x82, 0x01, 0x15, 0xb6, 0x12, 0xfa, 0x53, 0x6e, 0x05, 0x3e, 0x42, 0xb7, 0xe9, 0x10,
	0xaf, 0x8f, 0xda, 0x3a, 0xae, 0x7f, 0x74, 0xd5, 0xb8, 0xfa, 0x5b, 0xf6, 0xa6, 0x43, 0x3f, 0xce,
	0xe2, 0x27, 0x00, 0x00, 0xff, 0xff, 0x49, 0x0a, 0xf7, 0x6c, 0x46, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SongsServiceClient is the client API for SongsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SongsServiceClient interface {
	GetSongs(ctx context.Context, in *SongRequestParams, opts ...grpc.CallOption) (*GetSongsResponse, error)
}

type songsServiceClient struct {
	cc *grpc.ClientConn
}

func NewSongsServiceClient(cc *grpc.ClientConn) SongsServiceClient {
	return &songsServiceClient{cc}
}

func (c *songsServiceClient) GetSongs(ctx context.Context, in *SongRequestParams, opts ...grpc.CallOption) (*GetSongsResponse, error) {
	out := new(GetSongsResponse)
	err := c.cc.Invoke(ctx, "/song.SongsService/GetSongs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SongsServiceServer is the server API for SongsService service.
type SongsServiceServer interface {
	GetSongs(context.Context, *SongRequestParams) (*GetSongsResponse, error)
}

// UnimplementedSongsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSongsServiceServer struct {
}

func (*UnimplementedSongsServiceServer) GetSongs(ctx context.Context, req *SongRequestParams) (*GetSongsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSongs not implemented")
}

func RegisterSongsServiceServer(s *grpc.Server, srv SongsServiceServer) {
	s.RegisterService(&_SongsService_serviceDesc, srv)
}

func _SongsService_GetSongs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SongRequestParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SongsServiceServer).GetSongs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/song.SongsService/GetSongs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SongsServiceServer).GetSongs(ctx, req.(*SongRequestParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _SongsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "song.SongsService",
	HandlerType: (*SongsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSongs",
			Handler:    _SongsService_GetSongs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "song.proto",
}
